// gdx-extract `disk` subcommand (G-Diffuser R8 Step 1 — 64DD disk archive).
//
// Packs the whole 64DD Expansion Kit disk image into a small dedicated O2R archive
// (fzerox-disk.o2r) so the port no longer needs the raw .ndd file (nor the R7 managed copy) at
// runtime once a boot has reconstructed the image from the archive and proven byte-identity.
// See docs/investigation/2026-07-18/o2r-migration/R8_DISK_ARCHIVE_AND_DUMP_ALL_PLAN.md §Step 1.
//
// The archive carries these raw entries (no Torch resource header — plain blobs read back
// verbatim by the port's GDiffuser_LoadArchiveFileBytes / O2rArchive::LoadFile):
//   disk/identity = [u8 fmt][32-byte SHA-256 of the stored image].
//   disk/image    = the full 64,931,840-byte disk image, stored VERBATIM (see the normalize note
//                   below), deflated. Expect ~30-40 MB of compressed output.
//   ek/<symbol>   = (R8 Step 2, only when a slice manifest is supplied) one entry per named EK disk
//                   asset, carrying the RAW [diskOffset, diskOffset+len) slice of the image verbatim
//                   (MIO0-compressed textures stay compressed — same verbatim-slice philosophy). The
//                   symbol/offset/len come from port/gen/ek_slice_manifest.txt, which is generated by
//                   tools/gen_ek_assets.py from the SAME fill table (sEkAssetFills) the runtime
//                   gdx_ek_assets_fill copies, so an ek/<symbol> entry is byte-identical to the bytes
//                   the game loads at runtime. These entries let tools (Dump All) and the future EK
//                   modding seam read EK assets WITHOUT a loaded disk.
//
// Normalize note (verified against port/disk_buffer.cpp gdx_disk_load): unlike the cartridge ROM /
// 64DD IPL — which circulate as z64/v64/n64 dumps and the loader detects+normalizes — the disk
// loader performs NO byte-order swap on the disk buffer. It fread()s the .ndd and hands the raw
// bytes straight to gdx_leo_on_disk_loaded / gdx_ek_assets_fill. (The only swap in that function is
// the D_80769DF0 boot-logo TEXTURE fixup, which runs on the decoded texel array after the fill, not
// on the disk image.) 64DD disk dumps therefore have a single canonical byte order. This step
// mirrors the loader exactly: it stores the raw image and records fmt = 0 (native / as-is). Storing
// raw is also load-bearing for the boot-time deletion gate — SHA-256(disk/image) must equal the R7
// managed-copy SHA-256 (sidecar disk_sha256), which is computed over the .ndd's raw bytes.
//
// Output is written to <destDir>/fzerox-disk.o2r using the same deterministic miniz path
// (MINIZ_NO_TIME + pinned BEST_COMPRESSION level + sorted-entry insertion) the o2r/ipl subcommands
// rely on, so two runs against the same disk are byte-identical.
#pragma once

#include <string>

// Runs the disk extraction. Returns 0 on success, non-zero on any error (bad path, wrong-size
// image, archive write failure). On success writes <destDir>/fzerox-disk.o2r and prints the disk
// identity SHA-256 + entry sizes to stdout.
//
// manifestPath (R8 Step 2): optional path to port/gen/ek_slice_manifest.txt. When empty the archive
// carries exactly the two frozen disk/* entries (Step 1 behaviour). When supplied the manifest is
// REQUIRED to be readable and well-formed — an unreadable/malformed/out-of-range manifest is a hard
// error (non-zero return) so the runtime launcher keeps the raw-disk/managed-copy fallback rather
// than mount a partial archive. Every valid row adds one verbatim ek/<symbol> entry.
int GdxRunDiskExtract(const std::string& diskPath, const std::string& destDir,
                      const std::string& manifestPath = "");
